import type { DiscoveryRecord, Requirement } from "./types";

export const DISCOVERY_RECORDS: DiscoveryRecord[] = [
  {
    id: "PB-2026-0088",
    type: "brief",
    lane: "industrial",
    title: "Cut unplanned spindle downtime across a 40-machine shop floor",
    organisation: "Vardhman Precision Components · Chakan",
    value: "₹6,00,000",
    summary: "Detect ≥80% of bearing failures 72 hours ahead with under one false alarm per machine-month.",
    reason: "Retrofit diagnostics for machines without telemetry.",
    signal: "Budget confirmed · named decision owner",
  },
  {
    id: "RA-2026-0417",
    type: "asset",
    lane: "industrial",
    trl: 4,
    title: "Retrofit vibration diagnostics for bearing and spindle faults on legacy CNC machines",
    organisation: "Government engineering college · Pune district",
    value: "TRL 4",
    summary: "Precision 0.93 on a seeded-fault test rig; code and dataset published; mount geometry gated.",
    reason: "Clamp-on sensing, three named fault classes and no PLC changes.",
    signal: "Production-machine data still missing",
  },
  {
    id: "PB-2026-0112",
    type: "brief",
    lane: "industrial",
    title: "Raise post-consumer PET flake purity above 96% without adding sorting labour",
    organisation: "Reclaim Polymers · Vapi",
    value: "₹4,50,000",
    summary: "Existing line runs at 91–93% purity; bench proof required before a line trial.",
    reason: "Low-cost optical sorting on the existing conveyor.",
    signal: "Funded validation · 14 weeks",
  },
  {
    id: "RA-2026-0462",
    type: "asset",
    lane: "industrial",
    trl: 3,
    title: "Near-infrared classifier separating PET from PVC and PLA in mixed flake",
    organisation: "Institute of chemical technology · Mumbai",
    value: "TRL 3",
    summary: "94% bench accuracy on prepared flake; never tested on wet or contaminated feed.",
    reason: "Polymer discrimination on a moving belt.",
    signal: "Disclosure review required",
  },
  {
    id: "PB-2026-0149",
    type: "brief",
    lane: "software",
    title: "Digitise 1.2 lakh handwritten land mutation records into a searchable register",
    organisation: "State directorate of land records",
    value: "₹9,00,000",
    summary: "On-premise Indic OCR with field-level accuracy above 97% for names and survey numbers.",
    reason: "Handwritten Devanagari OCR with field extraction.",
    signal: "Public challenge · procurement route",
  },
  {
    id: "RA-2026-0521",
    type: "asset",
    lane: "software",
    trl: 5,
    title: "Layout-aware handwritten Devanagari OCR for legacy registers",
    organisation: "Engineering college · Nagpur",
    value: "TRL 5",
    summary: "96.4% field accuracy across 8,000 pages; deployed once with a municipal archive.",
    reason: "Matches script, on-premise constraint and field extraction.",
    signal: "Faculty attested · comparable pilot",
  },
];

export const REQUIREMENTS: Requirement[] = [
  {
    id: "R1",
    status: "met",
    requirement: "Clamp-on sensing, no spindle teardown and no PLC changes",
    evidence: "Mount design + rig photographs · asset v3",
    detail: "The sensor reads externally and the classifier runs on a separate gateway. The machine controller remains untouched.",
  },
  {
    id: "R2",
    status: "met",
    requirement: "Covers bearing faults, not only generic anomaly detection",
    evidence: "Bench report · three named fault classes",
    detail: "Outer-race, inner-race and cage defects are classified separately. Evidence is from seeded faults only.",
  },
  {
    id: "R3",
    status: "partial",
    requirement: "≥80% detection 72 hours ahead, below one false alarm per machine-month",
    evidence: "Have: 0.93 precision on 42 rig runs · Missing: lead-time measurement",
    detail: "The rig established whether a fault was present, not how early it became detectable.",
    resolution: "M1 baseline on four machines with historical logs, three weeks.",
  },
  {
    id: "R4",
    status: "partial",
    requirement: "Runs on an ARM edge gateway with 512 MB RAM and no cloud egress",
    evidence: "Have: 180 MB model and CPU inference · Missing: target-hardware run",
    detail: "Offline execution is supported in principle, but memory headroom has not been measured on the sponsor gateway.",
    resolution: "Sponsor provides one gateway for a two-day port test.",
  },
  {
    id: "R5",
    status: "gap",
    requirement: "Performance on production machines under two-shift load at 38–44 °C",
    evidence: "No evidence · all results are from one temperature-controlled test rig",
    detail: "Shop-floor noise, coolant mist and thermal drift are absent from the current dataset.",
    resolution: "Fund M1 and run on the production floor.",
  },
  {
    id: "R6",
    status: "pending",
    requirement: "Six months of labelled historical vibration logs",
    evidence: "Waiting on sponsor · blocked by NDA and data-sharing agreement",
    detail: "The sponsor has confirmed that logs exist for six machines, but failure labels are not yet confirmed.",
    resolution: "Sponsor countersigns the NDA and confirms labelling before M1.",
  },
];
