import { useCallback, useEffect, useState } from "react";
import { BadgeCheck, Building2, FileClock, FileUp, Link2, LockKeyhole, MessageCircle, Search, ShieldCheck, UserCheck } from "lucide-react";
import { Button, PageIntro, Pill } from "./components";

type User = { id:string; email:string; name:string; role:"researcher"|"company"|"officer"|"manager"; confirmationStatus:string; orcidId?:string|null };
type Tab = "account"|"research"|"files"|"messages"|"approvals"|"people";
const api = async <T,>(path:string, options?:RequestInit):Promise<T> => { const response=await fetch(path,{...options,headers:{"content-type":"application/json",...(options?.headers||{})}}); const value=await response.json(); if(!response.ok)throw new Error(value.error||"Something went wrong."); return value; };

export function Workspace() {
  const [user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true),[mode,setMode]=useState<"login"|"signup">("login"),[error,setError]=useState("");
  const [tab,setTab]=useState<Tab>("account");
  const refresh=useCallback(()=>api<{user:User|null}>("/api/account/me").then(v=>setUser(v.user)).catch(()=>setUser(null)).finally(()=>setLoading(false)),[]);
  useEffect(()=>{refresh();},[refresh]);
  async function submitAccount(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setError("");const data=Object.fromEntries(new FormData(event.currentTarget));try{await api(`/api/account/${mode}`,{method:"POST",body:JSON.stringify(data)});if(mode==="signup"){setMode("login");setError("Account created. Sign in to continue.");}else await refresh();}catch(e){setError((e as Error).message);}}
  if(loading)return <div className="page shell-width"><p>Opening your workspace…</p></div>;
  if(!user)return <div className="page shell-width auth-page"><section className="auth-story"><span className="hero__kicker"><ShieldCheck/> Protected workspace</span><h1>Your research work deserves a trusted room.</h1><p>Sign in to manage private files, messages, college decisions and research connections.</p><div className="trust-list"><span><LockKeyhole/> Private files stay protected</span><span><FileClock/> Important changes keep their history</span><span><UserCheck/> Roles need organisation confirmation</span></div></section><form className="auth-card" onSubmit={submitAccount}><div className="auth-switch"><button type="button" data-active={mode==="login"} onClick={()=>setMode("login")}>Sign in</button><button type="button" data-active={mode==="signup"} onClick={()=>setMode("signup")}>Create account</button></div>{mode==="signup"?<><label>Your name<input name="name" required/></label><label>Account type<select name="role" defaultValue="researcher"><option value="researcher">Researcher or student</option><option value="company">Company or public-body member</option><option value="officer">College approval officer</option></select></label></>:null}<label>Email<input name="email" type="email" required autoComplete="email"/></label><label>Password<input name="password" type="password" minLength={10} required autoComplete={mode==="login"?"current-password":"new-password"}/><small>At least 10 characters</small></label>{error?<p className="form-note">{error}</p>:null}<Button variant="primary" full>{mode==="login"?"Sign in":"Create my account"}</Button></form></div>;
  const tabs:Array<[Tab,string]>=[["account","Account"],["research","Research links"],["files","Files"],["messages","Messages"],["approvals","Approvals"],...(user.role==="officer"||user.role==="manager"?[["people","People"] as [Tab,string]]:[])];
  return <div className="page shell-width workspace-page"><PageIntro eyebrow="Protected workspace" title={`Hello, ${user.name}`}>
    Your account, private work and decisions are kept here. Important actions are recorded.
  </PageIntro><div className="workspace-status"><div><BadgeCheck/><span><strong>{user.role.replace("officer","approval officer")}</strong><small>{user.email}</small></span></div><Pill tone={user.confirmationStatus==="confirmed"?"verified":"warning"}>{user.confirmationStatus==="confirmed"?"Organisation confirmed":"Confirmation needed"}</Pill><Button onClick={async()=>{await api("/api/account/logout",{method:"POST"});setUser(null);}}>Sign out</Button></div><nav className="workspace-tabs" aria-label="Workspace sections">{tabs.map(([id,label])=><button key={id} data-active={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</nav>
    {tab==="account"?<Account user={user} refresh={refresh}/>:null}
    {tab==="research"?<ResearchConnections user={user}/>:null}
    {tab==="files"?<Files/>:null}
    {tab==="messages"?<Messages/>:null}
    {tab==="approvals"?<Approvals user={user}/>:null}
    {tab==="people"?<People/>:null}
  </div>;
}

function Account({user,refresh}:{user:User;refresh:()=>Promise<void>}){const[message,setMessage]=useState("");async function extra(e:React.FormEvent<HTMLFormElement>){e.preventDefault();try{await api("/api/account/extra-check",{method:"POST",body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});setMessage("Extra sign-in check complete for the next 10 minutes.");await refresh();}catch(x){setMessage((x as Error).message);}}return <div className="workspace-grid"><section className="workspace-card"><span className="eyebrow">Account status</span><h2>{user.confirmationStatus==="confirmed"?"Ready to represent your organisation":"Waiting for confirmation"}</h2><p>{user.confirmationStatus==="confirmed"?"Your approved powers are checked again before protected actions.":"You may prepare your profile. An approval officer must confirm your organisation and powers."}</p></section><form className="workspace-card" onSubmit={extra}><span className="eyebrow">Extra sign-in check</span><h2>Confirm before an important action</h2><p>Approvals and role changes require your password again.</p><label>Password<input type="password" name="password" required/></label><Button variant="primary">Confirm now</Button>{message?<p className="form-note">{message}</p>:null}</form></div>}

function ResearchConnections({user}:{user:User}){const[q,setQ]=useState(""),[results,setResults]=useState<Array<any>>([]),[note,setNote]=useState("");async function search(e:React.FormEvent){e.preventDefault();try{const v=await api<{results:Array<any>}>(`/api/openalex/search?q=${encodeURIComponent(q)}`);setResults(v.results);setNote("");}catch(x){setNote((x as Error).message);}}async function orcid(){try{const v=await api<{url:string}>("/api/orcid/start");location.href=v.url;}catch(x){setNote((x as Error).message);}}return <div className="workspace-grid"><section className="workspace-card"><span className="eyebrow">ORCID</span><h2>{user.orcidId?`Connected: ${user.orcidId}`:"Connect your research identity"}</h2><p>Bring in your public name and work history for review. Nothing becomes approved automatically.</p><Button variant="primary" onClick={orcid}><Link2/> {user.orcidId?"Reconnect ORCID":"Connect ORCID"}</Button></section><section className="workspace-card workspace-card--wide"><span className="eyebrow">OpenAlex</span><h2>Find papers and related work</h2><form className="inline-form" onSubmit={search}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Paper title, author or DOI" required/><Button variant="primary"><Search/> Search</Button></form>{note?<p className="form-note">{note}</p>:null}<div className="external-results">{results.map(r=><article key={r.id}><strong>{r.title}</strong><p>{r.authors.join(", ")} · {r.year||"Year unknown"}</p><small>Source: OpenAlex · checked {new Date(r.checkedAt).toLocaleDateString()}</small></article>)}</div></section></div>}

function Files(){const[files,setFiles]=useState<Array<any>>([]),[note,setNote]=useState("");const recordId="RA-2026-0417";const load=()=>api<{files:Array<any>}>(`/api/files?recordId=${recordId}`).then(v=>setFiles(v.files)).catch(()=>{});useEffect(()=>{void load();},[]);async function upload(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,file=(new FormData(form).get("file") as File);if(!file)return;const bytes=new Uint8Array(await file.arrayBuffer());let binary="";for(const b of bytes)binary+=String.fromCharCode(b);try{await api("/api/files",{method:"POST",body:JSON.stringify({recordId,name:file.name,contentType:file.type,accessLevel:(new FormData(form).get("accessLevel")),dataBase64:btoa(binary)})});setNote("File saved with a new version and unique mark.");form.reset();load();}catch(x){setNote((x as Error).message);}}return <div className="workspace-grid"><form className="workspace-card" onSubmit={upload}><span className="eyebrow">Add a file</span><h2>Choose who may open it</h2><label>File<input name="file" type="file" accept=".pdf,.txt,.csv,.json,.png,.jpg,.jpeg" required/></label><label>Access<select name="accessLevel"><option value="public">Public</option><option value="signed_in">People who signed in</option><option value="agreement">After an agreement</option><option value="named">Named people only</option></select></label><Button variant="primary"><FileUp/> Save protected file</Button>{note?<p className="form-note">{note}</p>:null}</form><section className="workspace-card workspace-card--wide"><span className="eyebrow">File history</span><h2>{recordId}</h2><div className="record-list">{files.map(f=><article key={f.id}><FileClock/><span><strong>{f.name}</strong><small>Version {f.version} · {f.accessLevel.replace("_"," ")} · {Math.ceil(f.size/1024)} KB</small><code>{f.checksum.slice(0,16)}…</code></span><a href={`/api/files/${f.id}`}>Open</a></article>)}{!files.length?<p>No files added yet.</p>:null}</div></section></div>}

function Messages(){const[messages,setMessages]=useState<Array<any>>([]),[kind,setKind]=useState("general_question");const contextId="MATCH-0417-0088";const load=()=>api<{messages:Array<any>}>(`/api/messages?contextType=match&contextId=${contextId}`).then(v=>setMessages(v.messages)).catch(()=>{});useEffect(()=>{void load();},[]);async function send(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,data=Object.fromEntries(new FormData(form));await api("/api/messages",{method:"POST",body:JSON.stringify({contextType:"match",contextId,kind,...data})});form.reset();load();}return <div className="workspace-grid"><form className="workspace-card" onSubmit={send}><span className="eyebrow">Message this match</span><h2>Keep the question with the work</h2><label>Message type<select value={kind} onChange={e=>setKind(e.target.value)}><option value="general_question">General question</option><option value="proof_request">Proof request</option><option value="company_information">Company information request</option><option value="college_decision">College decision request</option><option value="agreement">Agreement discussion</option><option value="test_update">Test update</option><option value="result">Result discussion</option></select></label><label>Message<textarea name="body" required rows={4}/></label><label>Due date<input type="date" name="dueAt"/></label><Button variant="primary"><MessageCircle/> Send message</Button></form><section className="workspace-card workspace-card--wide"><span className="eyebrow">Match conversation</span><h2>{contextId}</h2><div className="message-list">{messages.map(m=><article key={m.id}><div><strong>{m.authorName}</strong><Pill>{m.kind.replaceAll("_"," ")}</Pill></div><p>{m.body}</p><small>{new Date(m.created_at).toLocaleString()}{m.due_at?` · Due ${m.due_at}`:""}</small></article>)}{!messages.length?<p>No messages yet.</p>:null}</div></section></div>}

const approvalSteps=["people_named","ownership_checked","public_sharing","private_sharing","test_terms","complete"];
function Approvals({user}:{user:User}){const[items,setItems]=useState<Array<any>>([]),[note,setNote]=useState("");const recordId="RA-2026-0417";const load=()=>api<{approvals:Array<any>}>(`/api/approvals?recordId=${recordId}`).then(v=>setItems(v.approvals)).catch(()=>{});useEffect(()=>{void load();},[]);async function decide(e:React.FormEvent<HTMLFormElement>){e.preventDefault();try{await api("/api/approvals",{method:"POST",body:JSON.stringify({recordId,recordVersion:"v3",...Object.fromEntries(new FormData(e.currentTarget))})});setNote("Decision recorded with the version you reviewed.");load();}catch(x){setNote((x as Error).message);}}const latest=new Map(items.map(i=>[i.step,i]));return <div className="workspace-grid"><section className="workspace-card"><span className="eyebrow">Approval journey</span><h2>Research work · version 3</h2><ol className="approval-steps">{approvalSteps.map((s,i)=>{const a=latest.get(s);return <li key={s} data-done={a?.status==="approved"}><span>{a?.status==="approved"?"✓":i+1}</span><div><strong>{s.replaceAll("_"," ")}</strong><small>{a?`${a.status} by ${a.decidedByName}`:"Waiting"}</small></div></li>})}</ol></section>{user.role==="officer"||user.role==="manager"?<form className="workspace-card workspace-card--wide" onSubmit={decide}><span className="eyebrow">Record a separate decision</span><h2>Do not leave approval inside a message</h2><div className="form-grid"><label>Step<select name="step">{approvalSteps.map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</select></label><label>Decision<select name="status"><option value="approved">Approve</option><option value="rejected">Reject</option><option value="changes_requested">Ask for a change</option><option value="approved_with_limits">Approve with limits</option><option value="reassigned">Send to another officer</option></select></label><label>End date<input type="date" name="endsAt"/></label></div><label>Reason<textarea name="reason" required rows={3}/></label><label>Limits, if any<textarea name="limits" rows={2}/></label><Button variant="primary">Record decision</Button>{note?<p className="form-note">{note}</p>:null}</form>:<section className="workspace-card workspace-card--wide"><h2>Your college officer records decisions here</h2><p>You can see each decision, its reason, its end date and the exact version reviewed.</p></section>}</div>}

function People(){const[people,setPeople]=useState<Array<any>>([]),[note,setNote]=useState("");const load=()=>api<{people:Array<any>}>("/api/organisation/people").then(v=>setPeople(v.people)).catch(()=>{});useEffect(()=>{void load();},[]);async function confirm(id:string){try{await api(`/api/organisation/people/${id}`,{method:"POST",body:JSON.stringify({confirm:true,canUpload:true,canApproveSharing:false,canAgreeTest:false,canApprovePayment:false})});setNote("Person confirmed with upload permission only.");load();}catch(x){setNote((x as Error).message);}}return <section className="workspace-card"><span className="eyebrow">Organisation people</span><h2>Confirm identity and powers separately</h2>{note?<p className="form-note">{note}</p>:null}<div className="record-list">{people.map(p=><article key={p.id}><Building2/><span><strong>{p.name}</strong><small>{p.email} · {p.role} · {p.confirmationStatus}</small></span>{p.confirmationStatus!=="confirmed"?<Button onClick={()=>confirm(p.id)}>Confirm upload only</Button>:<Pill tone="verified">Confirmed</Pill>}</article>)}</div></section>}
